spring:
  application:
    name: shortlisted-management

  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    exchange: shortlisted_books_exchange
    addShortListedQueue: shortlisted_books_add_queue
    addShortListedRoutingKey: shortlisted_books_add_routingKey
    removeShortListedQueue: shortlisted_books_remove_queue
    removeShortListedRoutingKey: shortlisted_books_remove_routingKey
    log:
      console:
        level: debug


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8083